### ISSUE TITLE
ImportError: No module named 'html.parser'; 'html' is not a package

### ISSUE THREAD

**Issue by sjanssen2** [CAMI-challenge/OPAL#25]
I conda installed all dependencies in a fresh python=3.5 environment, but dendropy=4.3.0, which I pip installed, since I could not find a matching channel for this package.
Next, I cloned the sources and tried `python setup.py install`, which fails with the following error:
```
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import setup, find_packages
  File "/home/sjanssen/miniconda3/envs/opal/lib/python3.5/site-packages/setuptools/__init__.py", line 14, in <module>
    from setuptools.dist import Distribution, Feature
  File "/home/sjanssen/miniconda3/envs/opal/lib/python3.5/site-packages/setuptools/dist.py", line 24, in <module>
    from setuptools.depends import Require
  File "/home/sjanssen/miniconda3/envs/opal/lib/python3.5/site-packages/setuptools/depends.py", line 7, in <module>
    from .py33compat import Bytecode
  File "/home/sjanssen/miniconda3/envs/opal/lib/python3.5/site-packages/setuptools/py33compat.py", line 11, in <module>
    from setuptools.extern.six.moves import html_parser
  File "/home/sjanssen/miniconda3/envs/opal/lib/python3.5/site-packages/setuptools/_vendor/six.py", line 92, in __get__
    result = self._resolve()
  File "/home/sjanssen/miniconda3/envs/opal/lib/python3.5/site-packages/setuptools/_vendor/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/home/sjanssen/miniconda3/envs/opal/lib/python3.5/site-packages/setuptools/_vendor/six.py", line 82, in _import_module
    __import__(name)
ImportError: No module named 'html.parser'; 'html' is not a package

```

**Comment by sjanssen2** [comment]
I bet we are in the same situation as described here: https://stackoverflow.com/questions/28876791/importerror-no-module-named-html-parser-html-is-not-a-package-python3

**Comment by abremges** [comment]
This was resolved in https://github.com/CAMI-challenge/OPAL/pull/26, closing this.
