### ISSUE TITLE
conda dependencies

### ISSUE THREAD

**Issue by shenwei356** [CAMI-challenge/OPAL#43]
Hi Fernando,

I installed `cami-opal` with `conda` and got some error caused by `bokeh`.

<details>
<summary>log</summary>

```
2021-04-06 10:48:04,833 INFO Loading profiles...
2021-04-06 10:48:04,835 INFO done
2021-04-06 10:48:04,835 INFO Computing metrics...
2021-04-06 10:48:04,909 INFO done
2021-04-06 10:48:04,909 INFO Saving computed metrics...
2021-04-06 10:48:05,002 INFO done
2021-04-06 10:48:05,003 INFO Creating beta diversity plots...
2021-04-06 10:48:05,003 INFO done
2021-04-06 10:48:05,003 INFO Creating rarefaction curves...
2021-04-06 10:48:05,577 INFO done
2021-04-06 10:48:05,577 INFO Creating spider plots...
/home/shenwei/Public/app/miniconda3/envs/kmcp/lib/python3.9/site-packages/src/plots.py:340: UserWarning: FixedFormatter should only be used together with FixedLocator
  axs.set_xticklabels([''] + c.ALL_RANKS)
/home/shenwei/Public/app/miniconda3/envs/kmcp/lib/python3.9/site-packages/src/plots.py:340: UserWarning: FixedFormatter should only be used together with FixedLocator
  axs.set_xticklabels([''] + c.ALL_RANKS)
2021-04-06 10:48:05,926 INFO done
2021-04-06 10:48:05,926 INFO Computing rankings...
2021-04-06 10:48:05,981 INFO done
2021-04-06 10:48:05,981 INFO Creating HTML page...
Traceback (most recent call last):
  File "/home/shenwei/Public/app/miniconda3/envs/kmcp/bin/opal.py", line 377, in <module>
    main()
  File "/home/shenwei/Public/app/miniconda3/envs/kmcp/bin/opal.py", line 370, in main
    html.create_html(pd_rankings, ranks_scored, pd_metrics, labels, sample_ids_list, plots_list, output_dir, args.desc)
  File "/home/shenwei/Public/app/miniconda3/envs/kmcp/lib/python3.9/site-packages/src/html_opal.py", line 487, in create_html
    col_rankings = create_rankings_html(pd_rankings, ranks_scored)
  File "/home/shenwei/Public/app/miniconda3/envs/kmcp/lib/python3.9/site-packages/src/html_opal.py", line 187, in create_rankings_html
    weight_recall = Slider(start=0, end=10, value=1, step=.1, title=c.RECALL + " weight", callback=callback)
  File "/home/shenwei/Public/app/miniconda3/envs/kmcp/lib/python3.9/site-packages/bokeh/models/widgets/sliders.py", line 76, in __init__
    super().__init__(**kwargs)
  File "/home/shenwei/Public/app/miniconda3/envs/kmcp/lib/python3.9/site-packages/bokeh/model.py", line 236, in __init__
    super().__init__(**kwargs)
  File "/home/shenwei/Public/app/miniconda3/envs/kmcp/lib/python3.9/site-packages/bokeh/core/has_props.py", line 268, in __init__
    setattr(self, name, value)
  File "/home/shenwei/Public/app/miniconda3/envs/kmcp/lib/python3.9/site-packages/bokeh/core/has_props.py", line 304, in __setattr__
    raise AttributeError("unexpected attribute '%s' to %s, %s attributes are %s" %
AttributeError: unexpected attribute 'callback' to Slider, similar attributes are js_event_callbacks
```

</details>

The version of installed `bokeh` is `v2.3.0`, though the [recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/cami-opal/meta.yaml) of `cami-opal` requires`bokeh ==0.13.0`, which is only available for python 3.7.

    $ mamba install bokeh=0.13.0
    Problem: package bokeh-0.13.0-py37_0 requires python >=3.7,<3.8.0a0, but none of the providers can be installed

So, can you adapt `opal` to new bokeh, or simply requires python=3.7 in the conda recipe. 

Thank you!
Wei

**Comment by fernandomeyer** [comment]
Dear Wei,

thank you for reporting this. The conda recipe was now updated with python==3.7.

The issue, however, seemed to only occur if cami-opal was installed in an existing environment with python >3.7. If installed in a new environment, installation of the appropriate python version was triggered. Anyway, I hope that the change will avoid the version conflict.

Best,
Fernando

**Comment by shenwei356** [comment]
> The issue, however, seemed to only occur if cami-opal was installed in an existing environment with python >3.7. 

Right.

Thank you for this rapid reply.
